name: Chalice Automation Job

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
    - cron: '5-59/5 * * * *'
concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run reddit_daily.py
        run: python reddit_daily.py
        env:
          REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
          REDDIT_URL: ${{ secrets.REDDIT_URL }}
          REDDIT_U_AGENT: ${{ secrets.REDDIT_U_AGENT }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
